### ISSUE TITLE
Session ( :true ) parameter seems not working

### ISSUE THREAD

**Issue by gomez100** [Kyvis-Labs/ignition-api-client-module#3]
Trying to interface with Robot Studio (ABB) web services, with at least 5 seconds timer to mitigate the problem, the first request seems to be ok. From the second, the error received ( checked on wireshark  because it's non logged on the Gateway ) is errore 503 for ID not unique.

![image](https://github.com/user-attachments/assets/23269660-9289-4a17-9b8e-ed291608217e)
![image](https://github.com/user-attachments/assets/c74fb9e1-6fa9-4fa9-9a25-92b1744ccb26)

Postman is working fine, the difference seems to be the Cookie Section. 

![image](https://github.com/user-attachments/assets/fac40a02-b874-4dbe-bd70-409e7a96562a)

Tried to setup "session:true" on my YAML without success.

```
session: true

headers:
  - key: Accept
    value: application/xhtml+xml;v=2.0

variables:
  baseUrl:
    default: http://192.168.100.45:8880
    hidden: true

authType: 
  type: basic

functions:
  taskselection:
    url: "{{var::baseUrl}}/rw/rapid/taskselection?json=1"
    schedule:
      type: timer
      duration: 5
      unit: seconds
    actions:
      - action: tag
        path: "$._state"
        type: jsonExpand
  iosystem:
    url: "{{var::baseUrl}}/rw/iosystem/devices?json=1"
    schedule:
      type: timer
      duration : 5
      unit: seconds
    action:
      - action: tag
        path: "$._embedded._state"
        type: jsonExpand

```
